INSERT INTO `sekolah` (`nama_sekolah`, `alamat`, `jenjang`) VALUES
('SMA Negeri 1 Makassar', 'Jl. Sultan Alauddin No. 1, Makassar', 'SMA'),
('SMA Negeri 2 Makassar', 'Jl. AP Pettarani No. 10, Makassar', 'SMA'),
('SMA Negeri 3 Makassar', 'Jl. Urip Sumoharjo No. 20, Makassar', 'SMA'),
('SMA Negeri 4 Makassar', 'Jl. Perintis Kemerdekaan No. 30, Makassar', 'SMA'),
('SMA Negeri 5 Makassar', 'Jl. Veteran Selatan No. 40, Makassar', 'SMA'),
('SMA Negeri 6 Makassar', 'Jl. Andi Pangerang Pettarani No. 50, Makassar', 'SMA'),
('SMA Negeri 1 Gowa', 'Jl. Sultan Hasanuddin No. 5, Gowa', 'SMA'),
('SMA Negeri 2 Gowa', 'Jl. Baso Daeng Patompo No. 15, Gowa', 'SMA'),
('SMA Negeri 1 Maros', 'Jl. Dr. Ratulangi No. 25, Maros', 'SMA'),
('SMA Negeri 1 Takalar', 'Jl. Jenderal Sudirman No. 35, Takalar', 'SMA'),
('SMK Negeri 1 Makassar', 'Jl. Sultan Alauddin No. 60, Makassar', 'SMK'),
('SMK Negeri 2 Makassar', 'Jl. Pettarani No. 70, Makassar', 'SMK'),
('SMK Negeri 3 Makassar', 'Jl. Perintis Kemerdekaan No. 80, Makassar', 'SMK'),
('SMK Negeri 4 Makassar', 'Jl. Urip Sumoharjo No. 90, Makassar', 'SMK'),
('SMK Negeri 5 Makassar', 'Jl. Veteran Utara No. 100, Makassar', 'SMK'),
('SMK Negeri 6 Makassar', 'Jl. Monginsidi No. 110, Makassar', 'SMK'),
('SMK Negeri 1 Gowa', 'Jl. Sultan Hasanuddin No. 120, Gowa', 'SMK'),
('SMK Negeri 2 Gowa', 'Jl. Andi Pangerang Pettarani No. 130, Gowa', 'SMK'),
('SMK Negeri 1 Maros', 'Jl. Jenderal Sudirman No. 140, Maros', 'SMK'),
('SMK Negeri 1 Takalar', 'Jl. Dr. Ratulangi No. 150, Takalar', 'SMK');
